
name: Conda package test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Conda
      uses: s-weigand/setup-conda@v1
    - run: conda --version
    - run: which python
    - run: |
        cd ./java-dist
        conda env create -n beakerx -f configuration.yml
        conda activate beakerx
        (pip install -r requirements.txt --verbose)
        beakerx_kernel_java install
        cd ..

