
name: Conda package test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Set up Conda
      uses: s-weigand/setup-conda@v1
    - name: Cache gradle
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Cache Conda
      uses: actions/cache@v1
      with:
        path: ~/.conda
        key: ${{ runner.os }}-conda-${{ hashFiles('**/configuration.yml') }}
        restore-keys: |
          ${{ runner.os }}-conda-          
    - name: Verify conda version
      run: conda --version
    - name: Checkout beakerx_kernel_base repo
      uses: actions/checkout@v2
      with:
        repository: twosigma/beakerx_kernel_base
        path: beakerx_kernel_base
    - name: Build BeakerX Kernel Base
      run: |
        cd $GITHUB_WORKSPACE/beakerx_kernel_base
        chmod +x gradlew
        ./gradlew install
    - name: Update conda package
      run: |
        cd java-dist
        conda env update -f configuration.yml
    - name: Build BeakerX Java Kernel
      run: |
        chmod +x gradlew
        cd java-dist
        conda activate beakerx_kernel_java
        pip install -r requirements.txt --verbose
        beakerx_kernel_java install

